### ISSUE TITLE
Copy Paste editor line 

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#371] opened 2020-07-01 16:23 UTC
Copy line in one viz editor does not paste in other viz editor
 with " CTRL+c"  and  " CTRL+v". Also does not paste outside VizHub like in browser.

**Comment by curran** [comment] 2020-07-01 17:46
Copy-paste works as expected (with CTRL+c and CTRL+v) if you're not in Vim mode.

Vim mode does copy-pasting with Vim commands Y and P.

**Comment by curran** [comment] 2020-07-01 18:28
ALT+p

**Comment by nitanagdeote** [comment] 2020-07-01 18:54
Are you sure? It's not working.

**Comment by curran** [comment] 2020-07-01 20:31
Sorry - ALT+v

**Comment by curran** [comment] 2020-07-02 19:20
Closing as a duplicate of https://github.com/datavis-tech/vizhub-issue-tracker/issues/254, since this confusion resulted from the original confusion about being in Vim mode or not.

**Closed by curran** 2020-07-02 19:20 UTC
