### ISSUE TITLE
Search button in profile page.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#330] opened 2020-06-20 15:09 UTC
As the search feature for home page is done, a search feature for profile page to find the viz or person will be great.

**Comment by curran** [comment] 2020-06-22 19:52
Great idea!

Currently CTRL+F works pretty well on a profile page.

**Comment by curran** [comment] 2020-07-01 21:39
Closing as duplicate of *Search within Profile* #270

**Closed by curran** 2020-07-01 21:39 UTC
