### ISSUE TITLE
As a Vizhub admin, I would like to see feature usage analytics.

### ISSUE THREAD

**Issue by mmeigooni** [datavis-tech/vizhub-issue-tracker#598] opened 2020-11-21 00:18 UTC
Private Vizzes
Public Vizzes
Export
Number of forks
Real-time Collaboration?
Unfurling -- bit.ly style tracking of the link?

**Comment by mmeigooni** [comment] 2020-11-21 00:19
From Curran:
> This is probably something we should add - analytics on particular feature usage. Google Analytics, or maybe something in-house we can build on MongoDB

**Comment by curran** [comment] 2020-12-04 15:34
Some technical ideas:
 * We have a new collection with analytics timeseries data.
 * We use the direct MongoDB driver https://www.npmjs.com/package/mongodb
 * For each event we want to track, we can multiple timeseries datasets, at different levels of detail.
 * For example: `pageview` - top level timeseries for all page views of any kind
 * For example: `pageview.viz` - timeseries for just viz page views
 * For example: `pageview.viz.user:${userID}` - timeseries for viz page views across one particular user - we could expose this to end users actually, something like a "My Stats" page.
 * For example: `pageview.viz.user:${userID}.viz:${vizID}` - timeseries for viz page views of one particular viz - could expose a sparkline on each viz
 * For example: `fork` - timeseries for all fork events
 * ... etc. We could spend more time designing this set of timeseries, once a first version of something is working.

**Comment by curran** [comment] 2020-12-05 15:58
I've implemented the core of this scheme here https://github.com/curran/multiscale-timeseries

**Comment by curran** [comment] 2020-12-05 23:20
Technical foundation is laid down here: https://github.com/curran/vizhub/pull/396

Expanding on the original set of usage events from @mmeigooni :

Things that are not timeseries, but instead can come from direct database queries
 * Current count of Private Vizzes
 * Current count of Public Vizzes

Things that are timeseries, that fit into this new event collection scheme:

 * Export - track an event when a user exports a viz. Can track this in total, or broken down by viz author user, by viz, and by the user who exports.
 * Fork - track an event when a viz is forked. Can track this in total, or broken down by viz author user, by viz, and by the user who forks.
 * Real-time Collaboration - track an event when a collaborator is added, and when a collaborator is removed.
 * Unfurling - Yes, we can track an event whenever an unfurl occurs.

**Comment by curran** [comment] 2020-12-21 13:18
@mmeigooni First pass is live https://vizhub.com/stats

Additional numbers from the database today:
 * Total unique logins: 5,788
 * Total visualizations: 29,347
 * Private visualizations: 678

**Comment by curran** [comment] 2021-05-15 17:02
Closing as duplicate of VizHub Stats Page #623

**Closed by curran** 2021-05-15 17:02 UTC
