### ISSUE TITLE
No loading icon on mobile

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#525] opened 2020-10-22 20:25 UTC
Compare this screenshot with the desktop version.loading icon is missing in mobile

![Screenshot_20201010-005532_Chrome.jpg](https://user-images.githubusercontent.com/13540669/96926119-2c36eb00-1483-11eb-9632-474fb0ed36b1.jpg)

**Comment by curran** [comment] 2020-10-22 20:46
The loading icon (meaning the play/pause/run timer indicator) is also not there on desktop, until you open the editor.

https://vizhub.com/josvin92/e2ba10d0a2344c32b641d75b196e6ce8

![image](https://user-images.githubusercontent.com/68416/96928122-1bd43f80-1486-11eb-8882-a5fbeb35d2dc.png)

**Comment by curran** [comment] 2021-05-15 17:46
Closing as duplicate of Always Show Run Timer on Remote Edits #528

**Closed by curran** 2021-05-15 17:46 UTC
