### ISSUE TITLE
The search option goes away after showing the results.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#721] opened 2021-02-08 21:08 UTC
![no_search_option](https://user-images.githubusercontent.com/13540669/107281704-f9ac0080-6a27-11eb-998a-505348c59cf9.png)

**Comment by curran** [comment] 2021-02-08 21:17
Closing as duplicate of https://github.com/datavis-tech/vizhub-issue-tracker/issues/660

**Closed by curran** 2021-02-08 21:17 UTC
