### ISSUE TITLE
Profile analytics

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#431] opened 2020-07-21 14:37 UTC
To understand the activity of user, it will great to have a line chart of activity over time.It can be place in a link on profile like "summary" or something.
This feature will be useful for the user and the VizHub team to analyze.

**Comment by curran** [comment] 2020-08-01 17:53
Closing as duplicate of https://github.com/datavis-tech/vizhub-issue-tracker/issues/124

**Closed by curran** 2020-08-01 17:53 UTC
