### ISSUE TITLE
summary Almost 1000 forks 

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#408] opened 2020-07-20 03:14 UTC
Checked curran's html template has more than 1000 froks.when click on that doesnt load on mobile. Is it going to show all the forks after clicking?

**Comment by curran** [comment] 2020-07-20 13:21
What exactly did you click on?

If I click on the "100 forks" text in a preview, it works for me, on mobile.

Closing as cannot reproduce. Feel free to reopen if you can provide a way to reproduce.

**Closed by curran** 2020-07-20 13:21 UTC
