### ISSUE TITLE
A bug: too many compilation errors

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#380] opened 2020-07-02 21:01 UTC
So when I am changing the code and I know what I am changing, If there is pause in writing the code it gets compiled and error is showed. If I continue like this lot of errors get accumulated and they don't go away until you refresh the page. Can not recreate the error, but happen all the time.

**Comment by curran** [comment] 2020-07-02 21:16
Ok. The console _should_ be getting cleared out. Let me check...

**Comment by curran** [comment] 2020-07-02 21:45
Looks like it's getting cleared. Closing as not possible to reproduce.

**Closed by curran** 2020-07-02 21:45 UTC
