### ISSUE TITLE
Anonymous user feature, anybody should be able to try vizhub without log in.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#526] opened 2020-10-22 20:37 UTC
Check this **codepen**  
![captainAnonymous](https://user-images.githubusercontent.com/13540669/96927479-1c200b00-1485-11eb-8e53-1aef45d7f6c3.png)
page.

**Comment by curran** [comment] 2020-10-22 20:47
Duplicate of #445

**Closed by curran** 2020-10-22 20:47 UTC
