### ISSUE TITLE
I always come across this error but can not reproduce

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#640] opened 2020-12-09 18:25 UTC
Sometimes if I have a lot of errors. Even I fix the code after that the error is still there. The code should be working but it doesn't. Then I refresh the page and it works. And I don't know how to reproduce this.

**Comment by curran** [comment] 2020-12-09 20:33
Try to reproduce please. Even in general terms. If we can't reproduce it we can't fix it.

**Comment by waseem-medhat** [comment] 2020-12-09 21:11
It occasionally happens with me, too. My guess is that the auto-reload breaks after too quick (or too frequent) changes in the code before a reload is done. Maybe we can confirm or at least rule it out with the auto-run toggle.

**Comment by curran** [comment] 2020-12-09 22:34
Good to know! I wish I had a sequence of specific steps to follow to reproduce it. Then we can look more deeply into what's going on.

**Comment by curran** [comment] 2021-05-15 21:34
Would love to reproduce and fix this.

**Comment by curran** [comment] 2021-05-15 21:34
Closing as cannot reproduce.

**Closed by curran** 2021-05-15 21:34 UTC
