### ISSUE TITLE
search icon is gone after search results appeared

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#668] opened 2020-12-19 22:28 UTC
![searchIconGone](https://user-images.githubusercontent.com/13540669/102700927-bac7ae80-421f-11eb-8703-0151a86b8cb2.png)

**Comment by curran** [comment] 2021-02-08 21:17
Closing as duplicate of #660

**Closed by curran** 2021-02-08 21:17 UTC
