### ISSUE TITLE
THis file not showing me error

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#609] opened 2020-11-29 15:29 UTC
https://vizhub.com/nitanagdeote/3271bd40e0ed48f9adf7893fdaa2d567?edit=files&file=index.html&line

In this file, script tags are not paired, still not showing any error

**Comment by curran** [comment] 2020-11-30 15:43
Duplicate of #603

**Closed by curran** 2020-11-30 15:43 UTC
