### ISSUE TITLE
'Keyword' search feature

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#374] opened 2020-07-01 19:26 UTC
In addition to user name search feature a keyword search feature will be of great help, in a scenario like searching for a old viz and you don't want to search each and every viz

**Comment by curran** [comment] 2020-07-01 20:32
How would this differ from what the search does now?

Here's an example keyword search for "map" https://vizhub.com/search?query=map

**Comment by nitanagdeote** [comment] 2020-07-01 21:00
Well I am searching for file name "NavBar" in my profile page. I can not find it.

**Comment by curran** [comment] 2020-07-01 21:39
Closing as duplicate of **Search within Profile** #270

**Closed by curran** 2020-07-01 21:39 UTC
Labels: enhancement
